import Link from "next/link";
import { notFound } from "next/navigation";

import { ConsultationForm } from "@/components/consultation-request-form";
import { ConsultationButton, localPath, SiteShell } from "@/components/site-shell";
import { brandContent } from "@/lib/brand-content";
import { getUniversityShowcase, getUniversityShowcases } from "@/lib/public-api";
import { articles, countryGuides, faqItems, fixtureUniversities, type Locale, services, siteCopy } from "@/lib/site-content";

const copy = { fa: { faq: "پرسش‌های مرتبط", steps: "روند همکاری", audience: "این خدمت برای چه کسانی مناسب است؟", sources: "منابع و یادداشت محتوا", notFound: "صفحه موردنظر پیدا نشد." }, en: { faq: "Related questions", steps: "How it works", audience: "Who this is for", sources: "Sources and editorial notes", notFound: "We could not find that page." } };

function Hero({ eyebrow, title, text, action, secondary }: { eyebrow: string; title: string; text: string; action?: React.ReactNode; secondary?: React.ReactNode }) {
  return <section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-text">{text}</p><div className="hero-actions">{action}{secondary}</div></div><div className="hero-art" aria-hidden="true"><span /><span /><span /></div></div></section>;
}
function Section({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="section"><div className="shell"><div className="section-heading"><h2>{title}</h2>{action}</div>{children}</div></section>; }
function FaqList({ locale }: { locale: Locale }) { return <div className="faq-list">{faqItems[locale].map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div>; }
function ConversionBand({ locale, source }: { locale: Locale; source: string }) { const dictionary = siteCopy[locale]; return <section className="conversion-band"><div className="shell conversion-inner"><div><p className="eyebrow">JAHAN ACADEMY</p><h2>{locale === "fa" ? "برای قدم بعدی آماده‌اید؟" : "Ready for the next step?"}</h2><p>{dictionary.consultationText}</p></div><ConsultationButton locale={locale} source={source} /></div></section>; }
function UniversityCards({ locale, universities = fixtureUniversities }: { locale: Locale; universities?: Awaited<ReturnType<typeof getUniversityShowcases>> }) { const dictionary = siteCopy[locale]; return <div className="card-grid university-grid">{universities.map((university) => <article className="card university-card" key={university.slug}><div className="university-monogram" aria-hidden="true">JA</div><p className="card-meta">{university.country[locale]}{university.city ? ` · ${university.city[locale]}` : ""}</p><h3>{university.name[locale]}</h3><p>{university.summary[locale]}</p><Link href={localPath(locale, `/universities/${university.slug}`)}>{dictionary.viewDetails} <span aria-hidden="true">←</span></Link></article>)}</div>; }
function ArticleCard({ locale, article }: { locale: Locale; article: (typeof articles)[number] }) { return <article className="article-card"><p className="card-meta">{article.type === "news" ? (locale === "fa" ? "خبر" : "News") : (locale === "fa" ? "راهنما" : "Guide")} · {article.date}</p><h3>{article.title[locale]}</h3><p>{article.excerpt[locale]}</p><Link href={localPath(locale, `/${article.type === "news" ? "news" : "articles"}/${article.slug}`)}>{siteCopy[locale].readMore}</Link></article>; }

export async function HomePage({ locale }: { locale: Locale }) {
  const dictionary = siteCopy[locale]; const universities = await getUniversityShowcases(locale);
  return <SiteShell locale={locale}><main><Hero eyebrow={dictionary.heroEyebrow} title={dictionary.heroTitle} text={dictionary.heroText} action={<ConsultationButton locale={locale} source="home-hero" />} secondary={<Link className="button button-secondary" href={localPath(locale, "/countries")}>{dictionary.explore}</Link>} />
    <Section title={dictionary.trustTitle}><div className="trust-grid"><div className="trust-copy"><p>{dictionary.trustText}</p><Link className="text-link" href={localPath(locale, "/about")}>{dictionary.viewDetails}</Link></div><div className="trust-points">{["01", "02", "03"].map((number, index) => <div key={number}><strong>{number}</strong><span>{locale === "fa" ? ["مشاوره تخصصی", "اطلاعات روشن", "همراهی انسانی"][index] : ["Expert consultation", "Clear information", "Human support"][index]}</span></div>)}</div></div></Section>
    <Section title={dictionary.servicesTitle} action={<Link className="text-link" href={localPath(locale, "/services")}>{dictionary.browseAll}</Link>}><div className="card-grid">{services.map((service) => <Link className="card service-card" href={localPath(locale, `/services/${service.slug}`)} key={service.slug}><span className="service-icon">{service.icon}</span><h3>{service.title[locale]}</h3><p>{service.summary[locale]}</p><span>{dictionary.viewDetails}</span></Link>)}</div></Section>
    <Section title={dictionary.destinationsTitle} action={<Link className="text-link" href={localPath(locale, "/countries")}>{dictionary.browseAll}</Link>}><div className="card-grid destination-grid">{countryGuides.map((guide) => <Link key={guide.slug} className="destination-card" href={localPath(locale, `/countries/${guide.slug}`)}><span>{guide.title[locale]}</span><small>{guide.summary[locale]}</small></Link>)}</div></Section>
    <Section title={dictionary.universitiesTitle} action={<Link className="text-link" href={localPath(locale, "/universities")}>{dictionary.browseAll}</Link>}><UniversityCards locale={locale} universities={universities.slice(0, 3)} /></Section>
    <Section title={dictionary.articlesTitle} action={<Link className="text-link" href={localPath(locale, "/articles")}>{dictionary.browseAll}</Link>}><div className="article-grid">{articles.slice(0, 2).map((article) => <ArticleCard key={article.slug} locale={locale} article={article} />)}</div></Section><Section title={dictionary.faqTitle}><FaqList locale={locale} /></Section><ConversionBand locale={locale} source="home-footer" /></main></SiteShell>;
}

function ConsultationPage({ locale, source }: { locale: Locale; source: string }) { const dictionary = siteCopy[locale]; return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={dictionary.consultationTitle} text={dictionary.consultationText} /><section className="section"><div className="shell form-layout"><aside><p className="eyebrow">01 · 02 · 03</p><h2>{locale === "fa" ? "از همین‌جا شروع کنید" : "Start here"}</h2><p>{locale === "fa" ? "پس از ثبت اطلاعات، درخواست شما در پنل تیم ثبت می‌شود و با کد پیگیری قابل پیگیری است." : "After submission, your request is recorded for our team with a tracking code."}</p></aside><ConsultationForm locale={locale} source={source} /></div></section></main></SiteShell>; }

async function UniversitiesPage({ locale, slug }: { locale: Locale; slug?: string }) {
  const dictionary = siteCopy[locale];
  if (slug) { const university = await getUniversityShowcase(slug, locale); if (!university) notFound(); return <SiteShell locale={locale}><main><Hero eyebrow={university.country[locale]} title={university.name[locale]} text={university.summary[locale]} action={<ConsultationButton locale={locale} source={`university:${university.slug}`} />} /><section className="section"><div className="shell detail-grid"><div className="facts">{university.city && <Fact label={locale === "fa" ? "شهر" : "City"} value={university.city[locale]} />}{university.institutionType && <Fact label={locale === "fa" ? "نوع مؤسسه" : "Institution type"} value={university.institutionType[locale]} />}{university.foundedYear && <Fact label={locale === "fa" ? "سال تأسیس" : "Founded"} value={String(university.foundedYear)} />}</div><article className="prose"><h2>{locale === "fa" ? "درباره این دانشگاه" : "About this university"}</h2><p>{university.summary[locale]}</p>{university.websiteUrl && <a className="button button-secondary" href={university.websiteUrl} target="_blank" rel="noreferrer">{locale === "fa" ? "وب‌سایت رسمی" : "Official website"}</a>}</article></div></section><Section title={copy[locale].faq}><FaqList locale={locale} /></Section><ConversionBand locale={locale} source={`university:${university.slug}:footer`} /></main></SiteShell>; }
  const universities = await getUniversityShowcases(locale); return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={dictionary.universitiesTitle} text={locale === "fa" ? "معرفی‌های کوتاه و تأییدشده برای شروع شناخت؛ تصمیم‌گیری دقیق در مشاوره انجام می‌شود." : "Approved, concise introductions for orientation; detailed decisions belong in a consultation."} action={<ConsultationButton locale={locale} source="universities" />} /><Section title={dictionary.universitiesTitle}><UniversityCards locale={locale} universities={universities} /></Section></main></SiteShell>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }

function CountriesPage({ locale, slug }: { locale: Locale; slug?: string }) { const dictionary = siteCopy[locale]; const guide = slug ? countryGuides.find((entry) => entry.slug === slug) : undefined; if (slug && !guide) notFound(); if (guide) return <SiteShell locale={locale}><main><Hero eyebrow={locale === "fa" ? "راهنمای مقصد" : "Destination guide"} title={guide.title[locale]} text={guide.summary[locale]} action={<ConsultationButton locale={locale} source={`country:${guide.slug}`} />} /><section className="section"><div className="shell detail-grid"><div className="facts">{guide.facts[locale].map((fact) => <Fact key={fact.label} {...fact} />)}</div><article className="prose">{guide.sections[locale].map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}<h2>{copy[locale].sources}</h2><p>{locale === "fa" ? "محتوای نهایی پس از بررسی و تأیید تیم محتوا منتشر می‌شود." : "Final editorial content is published after review and approval by the content team."}</p></article></div></section><Section title={copy[locale].faq}><FaqList locale={locale} /></Section><ConversionBand locale={locale} source={`country:${guide.slug}:footer`} /></main></SiteShell>; return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={dictionary.destinationsTitle} text={locale === "fa" ? "راهنماهای مقدماتی برای طرح پرسش‌های درست پیش از مشاوره." : "Initial guides to help you bring the right questions to a consultation."} action={<ConsultationButton locale={locale} source="countries" />} /><Section title={dictionary.destinationsTitle}><div className="card-grid destination-grid">{countryGuides.map((entry) => <Link key={entry.slug} className="destination-card" href={localPath(locale, `/countries/${entry.slug}`)}><span>{entry.title[locale]}</span><small>{entry.summary[locale]}</small></Link>)}</div></Section></main></SiteShell>; }

function ServicesPage({ locale, slug }: { locale: Locale; slug?: string }) { const dictionary = siteCopy[locale]; const service = slug ? services.find((entry) => entry.slug === slug) : undefined; if (slug && !service) notFound(); if (service) return <SiteShell locale={locale}><main><Hero eyebrow={locale === "fa" ? "خدمات جهان آکادمی" : "Jahan Academy services"} title={service.title[locale]} text={service.summary[locale]} action={<ConsultationButton locale={locale} source={`service:${service.slug}`} />} /><Section title={copy[locale].steps}><div className="steps">{[1, 2, 3].map((step) => <div key={step}><strong>0{step}</strong><h3>{locale === "fa" ? ["گفت‌وگوی اولیه", "بررسی شرایط", "تعیین قدم بعدی"][step - 1] : ["Initial conversation", "Review your context", "Define the next step"][step - 1]}</h3></div>)}</div></Section><Section title={copy[locale].audience}><div className="prose"><p>{locale === "fa" ? "این خدمت برای افرادی طراحی شده است که می‌خواهند پیش از هر اقدام، مسیر مناسب خود را با راهنمایی تخصصی بررسی کنند." : "This service is for people who want expert guidance before deciding on the next academic-migration action."}</p></div></Section><Section title={copy[locale].faq}><FaqList locale={locale} /></Section><ConversionBand locale={locale} source={`service:${service.slug}:footer`} /></main></SiteShell>; return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={dictionary.servicesTitle} text={locale === "fa" ? "از شناخت مسیر تا آماده‌سازی گام بعدی، با شما همراهیم." : "From understanding your path to preparing the next step, we are here to help."} action={<ConsultationButton locale={locale} source="services" />} /><Section title={dictionary.servicesTitle}><div className="card-grid">{services.map((entry) => <Link className="card service-card" key={entry.slug} href={localPath(locale, `/services/${entry.slug}`)}><span className="service-icon">{entry.icon}</span><h3>{entry.title[locale]}</h3><p>{entry.summary[locale]}</p></Link>)}</div></Section></main></SiteShell>; }

function ContentPage({ locale, type, slug }: { locale: Locale; type: "article" | "news"; slug?: string }) { const dictionary = siteCopy[locale]; const items = articles.filter((item) => item.type === type); const article = slug ? items.find((item) => item.slug === slug) : undefined; if (slug && !article) notFound(); const title = type === "news" ? (locale === "fa" ? "اخبار" : "News") : (locale === "fa" ? "مقالات و راهنماها" : "Articles and guides"); if (article) return <SiteShell locale={locale}><main><Hero eyebrow={`${type === "news" ? "NEWS" : "GUIDE"} · ${article.date}`} title={article.title[locale]} text={article.excerpt[locale]} action={<ConsultationButton locale={locale} source={`${type}:${article.slug}`} />} /><section className="section"><article className="shell prose article-prose"><p>{locale === "fa" ? "این نسخه، ساختار تجربهٔ محتوایی سایت را نمایش می‌دهد. متن نهایی دوزبانه پس از تأیید تیم محتوا و از CMS منتشر خواهد شد." : "This version demonstrates the content experience. Final bilingual copy will be published from the CMS after editorial approval."}</p><h2>{locale === "fa" ? "برای قدم بعدی آماده‌اید؟" : "Ready to start?"}</h2><p>{dictionary.consultationText}</p></article></section><ConversionBand locale={locale} source={`${type}:${article.slug}:footer`} /></main></SiteShell>; return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={title} text={locale === "fa" ? "محتوای روشن برای کمک به شکل‌گیری پرسش‌های درست پیش از مشاوره." : "Clear editorial content to help you ask better questions before a consultation."} action={<ConsultationButton locale={locale} source={type} />} /><Section title={title}><div className="article-grid">{items.map((item) => <ArticleCard key={item.slug} locale={locale} article={item} />)}</div></Section></main></SiteShell>; }

function BrandFaqPage({ locale }: { locale: Locale }) {
  const dictionary = siteCopy[locale];
  const brand = brandContent[locale];
  return <SiteShell locale={locale}><main>
    <Hero eyebrow="JAHAN ACADEMY" title={dictionary.faqTitle} text={brand.faqIntro} action={<ConsultationButton locale={locale} source="faq" />} />
    <Section title={dictionary.faqTitle}><div className="faq-list">{brand.faqs.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></Section>
  </main></SiteShell>;
}

function AboutPage({ locale }: { locale: Locale }) {
  const brand = brandContent[locale];
  return <SiteShell locale={locale}><main>
    <Hero eyebrow="JAHAN ACADEMY" title={locale === "fa" ? "درباره جهان آکادمی" : "About Jahan Academy"} text={brand.intro} action={<ConsultationButton locale={locale} source="about" />} />
    <Section title={brand.whyTitle}><div className="prose"><p>{brand.whyText}</p></div></Section>
    <section className="section"><article className="shell prose">
      <section><h2>{brand.missionTitle}</h2><p>{brand.missionText}</p></section>
      <section><h2>{brand.visionTitle}</h2><p>{brand.visionText}</p></section>
    </article></section>
    <Section title={brand.valuesTitle}><div className="card-grid">{brand.values.map((value) => <article className="card" key={value.title}><h3>{value.title}</h3><p>{value.text}</p></article>)}</div></Section>
  </main></SiteShell>;
}

function StaticPage({ locale, page }: { locale: Locale; page: "about" | "contact" | "faq" | "privacy" | "terms" }) {
  if (page === "about") return <AboutPage locale={locale} />;
  if (page === "faq") return <BrandFaqPage locale={locale} />;
  const dictionary = siteCopy[locale];
  if (page === "contact") return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={locale === "fa" ? "تماس با ما" : "Contact us"} text={locale === "fa" ? "برای شروع، درخواست مشاوره ثبت کنید تا تیم ما با شما در تماس باشد." : "Submit a consultation request to start the conversation with our team."} /><section className="section"><div className="shell form-layout"><aside><p className="eyebrow">CONTACT</p><h2>{locale === "fa" ? "برای شروع گفت‌وگو آماده‌اید؟" : "Ready to start a conversation?"}</h2><p>{dictionary.consultationText}</p></aside><ConsultationForm locale={locale} source="contact" /></div></section></main></SiteShell>;
  const title = page === "privacy" ? (locale === "fa" ? "حریم خصوصی" : "Privacy") : (locale === "fa" ? "قوانین استفاده" : "Terms of use");
  const text = locale === "fa" ? "نسخه نهایی این صفحه، پس از تأیید حقوقی و انتشار دوزبانه از CMS جایگزین می‌شود." : "The final legal copy will replace this version after bilingual legal approval and CMS publication.";
  return <SiteShell locale={locale}><main><Hero eyebrow="JAHAN ACADEMY" title={title} text={text} /><section className="section"><article className="shell prose"><h2>{title}</h2><p>{text}</p></article></section></main></SiteShell>;
}

export async function RoutedPublicPage({ locale, segments, source }: { locale: Locale; segments: string[]; source: string }) { const [root, slug] = segments; if (root === "consultation" && !slug) return <ConsultationPage locale={locale} source={source} />; if (root === "countries") return <CountriesPage locale={locale} slug={slug} />; if (root === "universities") return <UniversitiesPage locale={locale} slug={slug} />; if (root === "services") return <ServicesPage locale={locale} slug={slug} />; if (root === "articles") return <ContentPage locale={locale} type="article" slug={slug} />; if (root === "news") return <ContentPage locale={locale} type="news" slug={slug} />; if (!slug && ["about", "contact", "faq", "privacy", "terms"].includes(root)) return <StaticPage locale={locale} page={root as "about" | "contact" | "faq" | "privacy" | "terms"} />; notFound(); }
