// Panel-owned brand narrative supplied by the user on October 6, 2026.
// Bold spans are rendered as React <strong> elements, never as raw HTML.
export const aboutContent = {
  fa: {
    description: "جهان آکادمی؛ همراه بلندمدت برای رشد، از شناخت فرد و انتخاب آگاهانه تا تحصیل، مهاجرت و رشد حرفه‌ای. جهان رو شروع کن.",
    paragraphs: [
      "جهان آکادمی از یک تفاوت اساسی شروع می‌شود: ما خودمان را صرفاً یک مؤسسه مهاجرتی نمی‌بینیم. نقطه شروع ما جایی‌ست که بسیاری از مجموعه‌ها هنوز وارد ماجرا نشده‌اند؛ همان لحظه‌ای که مخاطب هنوز نمی‌داند کدام مسیر، کدام کشور یا حتی کدام آینده برای او درست‌تر است. ما از «فروش مقصد» فاصله گرفته‌ایم و روی ساختن مسیر تمرکز کرده‌ایم؛ مسیری که از شناخت فرد شروع می‌شود، به انتخاب آگاهانه می‌رسد و تا تحصیل، ورود به بازار کار، مهاجرت و رشد حرفه‌ای ادامه پیدا می‌کند. برای همین، جهان آکادمی قرار نیست فقط یک پرونده را به نتیجه برساند؛ قرار است کمک کند هر تصمیم، بخشی از یک تصویر بزرگ‌تر از آینده باشد. همین نگاه است که برند را از یک واسطه خدماتی، به یک **همراه بلندمدت برای رشد** تبدیل می‌کند.",
      "آنچه این مسیر را ارزشمند می‌کند، فقط دانش و تجربه نیست؛ نحوه استفاده از آن‌هاست. در جهان آکادمی، تخصص باید به وضوح تبدیل شود، تجربه باید به تصمیم بهتر کمک کند و هر توصیه باید پشتوانه واقعی داشته باشد. ما با وعده‌های بزرگ، انتخاب را برای مخاطب جذاب‌تر نمی‌کنیم؛ با شفافیت، انتخاب را برایش روشن‌تر می‌کنیم. چون وقتی پای آینده یک انسان در میان است، اعتماد با تبلیغات ساخته نمی‌شود؛ با صداقت، دقت، همراهی و کیفیتی ساخته می‌شود که در تمام نقاط تماس برند احساس شود. هسته ارزش‌های جهان آکادمی نیز دقیقاً بر همین پایه شکل گرفته: **شفافیت، تخصص، انسان‌محوری، همراهی، رشد و نگاه جهانی.** این یعنی مخاطب نباید فقط حس کند با یک مجموعه حرفه‌ای روبه‌روست؛ باید احساس کند کسی روبه‌رویش ایستاده که هم جهان را می‌شناسد و هم اهمیت تصمیم او را.",
      "برای ما، مهاجرت پایان یک فرایند نیست؛ آغاز یک جهان تازه است. به همین دلیل «شروع» در مرکز هویت جهان آکادمی قرار دارد، نه «رفتن». ما به آدم‌هایی فکر می‌کنیم که می‌خواهند بیشتر ببینند، بیشتر تجربه کنند، حرفه‌ای‌تر رشد کنند و آینده‌ای فراتر از محدوده امروز خود بسازند. جهان آکادمی آمده تا این فاصله میان «خواستن» و «شروع کردن» را با شناخت، تجربه و همراهی واقعی پر کند؛ نه با نسخه‌های آماده، بلکه با مسیری که برای هر فرد معنا داشته باشد. **ما مهاجرت نمی‌فروشیم؛ آغاز می‌سازیم.** آغازی که روشن‌تر است، حساب‌شده‌تر است و شایسته آینده‌ای‌ست که قرار است ساخته شود. **جهان آکادمی — جهان رو شروع کن.**",
    ],
  },
  en: {
    description: "Jahan Academy is a long-term partner for growth, from understanding yourself and making informed choices to studying, migration, and professional development. Begin your world.",
    paragraphs: [
      "Jahan Academy begins with a fundamental difference: we do not see ourselves simply as a migration agency. Our starting point is a moment many organizations have yet to address: when someone still does not know which path, which country, or even which future is right for them. We have moved away from selling destinations and focus on building a path—one that begins with understanding the individual, leads to informed choices, and continues through education, entering the job market, migration, and professional growth. That is why Jahan Academy is here to do more than bring a case to completion; we help each decision become part of a bigger picture of the future. This perspective turns the brand from a service intermediary into a **long-term partner for growth**.",
      "What makes this path valuable is not just knowledge and experience, but how we use them. At Jahan Academy, expertise must bring clarity, experience must support better decisions, and every recommendation must have a real foundation. We do not make choices more appealing through grand promises; we make them clearer through transparency. When a person's future is at stake, advertising alone cannot build trust. Trust comes from honesty, care, support, and quality felt at every point of contact with the brand. Jahan Academy's core values rest on this foundation: **transparency, expertise, people first, support, growth, and a global perspective.** People should feel more than the presence of a professional organization; they should feel that someone understands both the world and the importance of their decision.",
      "For us, migration is not the end of a process; it is the beginning of a new world. That is why beginning, rather than leaving, is at the heart of Jahan Academy's identity. We think of people who want to see more, experience more, grow professionally, and build a future beyond the boundaries of their lives today. Jahan Academy is here to bridge the distance between wanting and beginning through understanding, experience, and real support—not with ready-made answers, but with a path that has meaning for each person. **We do not sell migration; we create beginnings.** Beginnings that are clearer, more considered, and worthy of the future ahead. **Jahan Academy—begin your world.**",
    ],
  },
};
